#!/bin/bash
rm -rf ./src
cp -r ./bak/src ./src
find ./src|while read FILE;do OUT=$(echo $FILE|sed "s/QuestionAnswer/Questionnaire/g");mv $FILE $OUT;done
#find ./src|while read FILE;do OUT=$(echo $FILE|sed "s/Question/Questionnaire/g");mv $FILE $OUT;done
#find ./src|while read FILE;do OUT=$(echo $FILE|sed "s/Answer/Submission/g");mv $FILE $OUT;done
history|grep sed
sed -i -e 's/QuestionAnswer/Questionnaire/g' $(find ./src|grep "\.ts$")
sed -i -e 's/questionAnswer/questionnaire/g' $(find ./src|grep "\.ts$")
#sed -i -e 's/Question/Questionnaire/g' $(find ./src|grep "\.ts$")
#sed -i -e 's/Answer/Submission/g' $(find ./src|grep "\.ts$")
