#!/bin/bash
rm -rf ./src
cp -r ./res/src ./src
find ./src|while read FILE;do OUT=$(echo $FILE|sed "s/QuestionAnswer/Questionnaire/g");mv $FILE $OUT;done
sed -i -e 's/QuestionAnswer/Questionnaire/g' $(find ./src|grep "\.ts$")
sed -i -e 's/questionAnswer/questionnaire/g' $(find ./src|grep "\.ts$")
sed -i -e 's/questionAnswer/questionnaire/g' $(find ./src|grep "\.ts$")
sed -i -e 's/questionanswer/questionnaire/g' $(find ./src|grep "\.ts$")
sed -i -e 's/\@aries-framework\/question-answer/\@entidad\/questionnaire/g' $(find ./src|grep "\.ts$")
